from .text_append_node import NODE_CLASS_MAPPINGS as TEXT_APPEND_NODE_CLASS_MAPPINGS
from .text_append_node import NODE_DISPLAY_NAME_MAPPINGS as TEXT_APPEND_NODE_DISPLAY_NAME_MAPPINGS
from .vramdebugplus import NODE_CLASS_MAPPINGS as VRAM_DEBUG_PLUS_NODE_CLASS_MAPPINGS
from .vramdebugplus import NODE_DISPLAY_NAME_MAPPINGS as VRAM_DEBUG_PLUS_NODE_DISPLAY_NAME_MAPPINGS
from .tensordebugplus import NODE_CLASS_MAPPINGS as TENSOR_DEBUG_PLUS_NODE_CLASS_MAPPINGS
from .tensordebugplus import NODE_DISPLAY_NAME_MAPPINGS as TENSOR_DEBUG_PLUS_NODE_DISPLAY_NAME_MAPPINGS
from .animation_schedule_output import NODE_CLASS_MAPPINGS as ANIMATION_SCHEDULE_OUTPUT_NODE_CLASS_MAPPINGS
from .animation_schedule_output import NODE_DISPLAY_NAME_MAPPINGS as ANIMATION_SCHEDULE_OUTPUT_NODE_DISPLAY_NAME_MAPPINGS
from .clipinterrogator import NODE_CLASS_MAPPINGS as CLIP_INTERROGATOR_NODE_CLASS_MAPPINGS
from .clipinterrogator import NODE_DISPLAY_NAME_MAPPINGS as CLIP_INTERROGATOR_NODE_DISPLAY_NAME_MAPPINGS
from .image_batcher import NODE_CLASS_MAPPINGS as IMAGE_BATCHER_NODE_CLASS_MAPPINGS
from .image_batcher import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_BATCHER_NODE_DISPLAY_NAME_MAPPINGS
from .text_search_node import NODE_CLASS_MAPPINGS as TEXT_SEARCH_NODE_CLASS_MAPPINGS
from .text_search_node import NODE_DISPLAY_NAME_MAPPINGS as TEXT_SEARCH_NODE_DISPLAY_NAME_MAPPINGS
from .LoadImagePlus import NODE_CLASS_MAPPINGS as LOAD_IMAGE_PLUS_NODE_CLASS_MAPPINGS
from .LoadImagePlus import NODE_DISPLAY_NAME_MAPPINGS as LOAD_IMAGE_PLUS_NODE_DISPLAY_NAME_MAPPINGS
from .LoadVideoPlus import NODE_CLASS_MAPPINGS as LOAD_VIDEO_PLUS_NODE_CLASS_MAPPINGS
from .LoadVideoPlus import NODE_DISPLAY_NAME_MAPPINGS as LOAD_VIDEO_PLUS_NODE_DISPLAY_NAME_MAPPINGS
from .deforum_animation_node import NODE_CLASS_MAPPINGS as DEFORUM_ANIMATION_NODE_CLASS_MAPPINGS
from .deforum_animation_node import NODE_DISPLAY_NAME_MAPPINGS as DEFORUM_ANIMATION_NODE_DISPLAY_NAME_MAPPINGS
from .load_unet import NODE_CLASS_MAPPINGS as LOAD_UNET_NODE_CLASS_MAPPINGS
from .load_unet import NODE_DISPLAY_NAME_MAPPINGS as LOAD_UNET_NODE_DISPLAY_NAME_MAPPINGS
#from .ipbin import NODE_CLASS_MAPPINGS as IPBIN_NODE_CLASS_MAPPINGS
#from .ipbin import NODE_DISPLAY_NAME_MAPPINGS as IPBIN_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **TEXT_APPEND_NODE_CLASS_MAPPINGS,
    **VRAM_DEBUG_PLUS_NODE_CLASS_MAPPINGS,
    **TENSOR_DEBUG_PLUS_NODE_CLASS_MAPPINGS,
    **ANIMATION_SCHEDULE_OUTPUT_NODE_CLASS_MAPPINGS,
    **CLIP_INTERROGATOR_NODE_CLASS_MAPPINGS,
    **IMAGE_BATCHER_NODE_CLASS_MAPPINGS,
    **TEXT_SEARCH_NODE_CLASS_MAPPINGS,
    **LOAD_IMAGE_PLUS_NODE_CLASS_MAPPINGS,
    **LOAD_VIDEO_PLUS_NODE_CLASS_MAPPINGS,
    **DEFORUM_ANIMATION_NODE_CLASS_MAPPINGS,
    **LOAD_UNET_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TEXT_APPEND_NODE_DISPLAY_NAME_MAPPINGS,
    **VRAM_DEBUG_PLUS_NODE_DISPLAY_NAME_MAPPINGS,
    **TENSOR_DEBUG_PLUS_NODE_DISPLAY_NAME_MAPPINGS,
    **ANIMATION_SCHEDULE_OUTPUT_NODE_DISPLAY_NAME_MAPPINGS,
    **CLIP_INTERROGATOR_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_BATCHER_NODE_DISPLAY_NAME_MAPPINGS,
    **TEXT_SEARCH_NODE_DISPLAY_NAME_MAPPINGS,
    **LOAD_IMAGE_PLUS_NODE_DISPLAY_NAME_MAPPINGS,
    **LOAD_VIDEO_PLUS_NODE_DISPLAY_NAME_MAPPINGS,
    **DEFORUM_ANIMATION_NODE_DISPLAY_NAME_MAPPINGS,
    **LOAD_UNET_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']