# __init__.py
from .text_append_node import NODE_CLASS_MAPPINGS as TEXT_APPEND_NODE_CLASS_MAPPINGS
from .text_append_node import NODE_DISPLAY_NAME_MAPPINGS as TEXT_APPEND_NODE_DISPLAY_NAME_MAPPINGS
from .vramdebugplus import NODE_CLASS_MAPPINGS as VRAM_DEBUG_PLUS_NODE_CLASS_MAPPINGS
from .vramdebugplus import NODE_DISPLAY_NAME_MAPPINGS as VRAM_DEBUG_PLUS_NODE_DISPLAY_NAME_MAPPINGS
from .tensordebugplus import NODE_CLASS_MAPPINGS as TENSOR_DEBUG_PLUS_NODE_CLASS_MAPPINGS
from .tensordebugplus import NODE_DISPLAY_NAME_MAPPINGS as TENSOR_DEBUG_PLUS_NODE_DISPLAY_NAME_MAPPINGS
from .animation_schedule_output import NODE_CLASS_MAPPINGS as ANIMATION_SCHEDULE_OUTPUT_NODE_CLASS_MAPPINGS
from .animation_schedule_output import NODE_DISPLAY_NAME_MAPPINGS as ANIMATION_SCHEDULE_OUTPUT_NODE_DISPLAY_NAME_MAPPINGS
#WIP from .clipinterrogator import NODE_CLASS_MAPPINGS as CLIP_INTERROGATOR_NODE_CLASS_MAPPINGS
#WIP from .clipinterrogator import NODE_DISPLAY_NAME_MAPPINGS as CLIP_INTERROGATOR_NODE_DISPLAY_NAME_MAPPINGS
#WIP from .image_batcher import NODE_CLASS_MAPPINGS as IMAGE_BATCHER_NODE_CLASS_MAPPINGS
#WIP from .image_batcher import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_BATCHER_NODE_DISPLAY_NAME_MAPPINGS
from .text_search_node import NODE_CLASS_MAPPINGS as TEXT_SEARCH_NODE_CLASS_MAPPINGS
from .text_search_node import NODE_DISPLAY_NAME_MAPPINGS as TEXT_SEARCH_NODE_DISPLAY_NAME_MAPPINGS
#WIP from .custom_emoji_menu_item_node import NODE_CLASS_MAPPINGS as CUSTOM_NODE_CLASS_MAPPINGS
#WIP from .custom_emoji_menu_item_node import NODE_DISPLAY_NAME_MAPPINGS as CUSTOM_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **TEXT_APPEND_NODE_CLASS_MAPPINGS,
    **VRAM_DEBUG_PLUS_NODE_CLASS_MAPPINGS,
    **TENSOR_DEBUG_PLUS_NODE_CLASS_MAPPINGS,
    **ANIMATION_SCHEDULE_OUTPUT_NODE_CLASS_MAPPINGS,
#WIP     **CLIP_INTERROGATOR_NODE_CLASS_MAPPINGS,
#WIP     **IMAGE_BATCHER_NODE_CLASS_MAPPINGS,
    **TEXT_SEARCH_NODE_CLASS_MAPPINGS,
#WIP     **CUSTOM_NODE_CLASS_MAPPINGS  # Add the new node class mappings
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TEXT_APPEND_NODE_DISPLAY_NAME_MAPPINGS,
    **VRAM_DEBUG_PLUS_NODE_DISPLAY_NAME_MAPPINGS,
    **TENSOR_DEBUG_PLUS_NODE_DISPLAY_NAME_MAPPINGS,
    **ANIMATION_SCHEDULE_OUTPUT_NODE_DISPLAY_NAME_MAPPINGS,
#WIP     **CLIP_INTERROGATOR_NODE_DISPLAY_NAME_MAPPINGS,
#WIP     **IMAGE_BATCHER_NODE_DISPLAY_NAME_MAPPINGS,
    **TEXT_SEARCH_NODE_DISPLAY_NAME_MAPPINGS,
#WIP    **CUSTOM_NODE_DISPLAY_NAME_MAPPINGS  # Add the new node display name mappings
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']